# Generated by Django 4.2.5 on 2023-11-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorregis',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=255)),
                ('Lname', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255, unique=True)),
                ('Phone_Number', models.IntegerField()),
                ('Password', models.CharField(max_length=255)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Authority_reg',
            },
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
