# Generated by Django 4.2.5 on 2023-11-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_authorregis_delete_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorregis',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
